### ISSUE TITLE
Ctrl+D drops an exception

### ISSUE THREAD

**Issue by jabbalaci** [jlp765/tnim#10]
It's common to quit a REPL with Ctrl+D (under Linux). However, tnim drops an error in this case:

    nim> 
    Error: unhandled exception: Linenoise returned nil [IOError]

For me, every REPL usage is a new session, thus Ctrl+D could trigger a \qc quit, i.e. clear the history and quit.

**Comment by jlp765** [comment]
Release 2.0.5 now does a \q (save and quit)
